---
- name: deploy_monitoring_config
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: update-system
      ansible.builtin.include_role:
        name: update-system

- name: Deploy ELK stack on main server
  hosts: elk_server
  become: true
  gather_facts: yes
  roles:
    - elk_server

- name: Deploy Beats agents on ELK clients
  hosts: elk_clients
  become: true
  gather_facts: yes
  roles:
    - beats_agents

# https://www.youtube.com/watch?v=XVRv1W3n94Y = | Install Elasticsearch, Logstash, Kibana, Filebeat Ubuntu