---
- name: Update packages on Debian-based systems
  ansible.builtin.apt:
    update_cache: yes
  retries: 5
  delay: 15
  register: apt_update
  until: apt_update is succeeded

- name: Autoremove unused packages (Debian)
  ansible.builtin.apt:
    autoremove: true
    autoclean: true
  become: true
 
- name: Check if a reboot is required (Debian-based)
  stat:
    path: /var/run/reboot-required
  register: debian_reboot_required
  
- name: Reboot the system if required
  ansible.builtin.reboot:
  when:  debian_reboot_required.stat.exists
  become: true 
    