---
- name: Gather installed packages facts
  ansible.builtin.package_facts:
    manager: auto

- name: Ensure python3-libdnf5 is installed
  when: "'python3-libdnf5' not in ansible_facts.packages"
  ansible.builtin.command: sudo dnf install -y python3-libdnf5

- name: Update RedHat-based systems (RHEL, CentOS, Fedora)
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_cache: true
  become: true

- name: Remove garbage packages of RedHat-based systems (RHEL, CentOS, Fedora)
  ansible.builtin.dnf:
    autoremove: true
  become: true