- name: Install prerequisites
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - gnupg
    state: present
  become: true

- name: Download and install Elasticsearch GPG key
  ansible.builtin.shell: |
    curl -fsSL https://artifacts.elastic.co/GPG-KEY-elasticsearch | gpg --dearmor -o /usr/share/keyrings/elasticsearch-keyring.gpg
  args:
    creates: /usr/share/keyrings/elasticsearch-keyring.gpg
  become: true

- name: Add Elasticsearch APT repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main"
    filename: elastic-8.x
    state: present
  become: true

- name: Update APT cache
  ansible.builtin.package:
    update_cache: yes
  become: true

- name: Install Filebeat | Metricbeat
  ansible.builtin.apt:
    name:
      - filebeat
      - metricbeat
    state: present
  become: true
