---
- name: Add Elastic GPG key
  ansible.builtin.rpm_key:
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present
  become: true

- name: Add Elastic YUM repository
  ansible.builtin.yum_repository:
    name: elastic-8.x
    description: Elastic 8.x repo
    baseurl: https://artifacts.elastic.co/packages/8.x/yum
    gpgcheck: yes
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    enabled: yes
  become: true

- name: Install Filebeat | Metricbeat
  ansible.builtin.dnf:
    name:
      - filebeat
      - metricbeat
    state: present
  become: true
