- name: Include distribution-specific variables
  ansible.builtin.include_vars:
    file: "{{ ansible_distribution }}.yml"

- name: ensure stack components can locate Java
  ansible.builtin.lineinfile:
    path: /etc/environment
    line: JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"
    create: yes

- name: Source environment
  shell: . /etc/environment

- name: Download and install Elasticsearch GPG key
  ansible.builtin.shell: |
    curl -fsSL https://artifacts.elastic.co/GPG-KEY-elasticsearch | gpg --dearmor -o /usr/share/keyrings/elasticsearch-keyring.gpg
  args:
    creates: /usr/share/keyrings/elasticsearch-keyring.gpg

- name: Add Elasticsearch APT repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main"
    filename: elastic-8.x
    state: present

- name: Update APT cache
  ansible.builtin.package:
    update_cache: yes

- name: Install required packages for Ubuntu as main server
  ansible.builtin.package:
    name: "{{ UbuntuServer_requirement_packages }}"
    state: present
    update_cache: yes

- name: Copy templated elasticsearch.yml
  template:
    src: elasticsearch.yml.j2
    dest: "{{ elasticsearch_config_path }}"
    owner: "{{ elasticsearch_owner }}"
    group: "{{ elasticsearch_group }}"
    mode: '0644'

- name: Copy templated kibana.yml
  template:
    src: kibana.yml.j2
    dest: "{{ kibana_config_path }}"
    owner: "{{ kibana_owner }}"
    group: "{{ kibana_group }}"
    mode: '0644'

- name: Deploy Filebeat configuration
  ansible.builtin.template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    owner: root
    group: root
    mode: '0644'

- name: Enable and start elasticsearch, logstash, kibana
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop:
    - elasticsearch
    - logstash
    - kibana
    - filebeat
    - metricbeat

- name: Enable Filebeat system module
  command: filebeat modules enable system
  args:
    creates: /etc/filebeat/modules.d/system.yml
  become: true

- name: Setup Filebeat dashboards and ingest pipelines
  command: filebeat setup
  become: true

- name: Load Filebeat dashboards
  command: filebeat setup --dashboards
  become: true

